name: Initialize
description: Check out Dart Sass and build the embedded protocol buffer.
inputs:
  github-token: {required: true}
  node-version: {required: false, default: 'lts/*'}
  dart-sdk: {required: false, default: stable}
  architecture: {required: false}
runs:
  using: composite
  steps:
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: "${{ inputs.dart-sdk }}"
        architecture: "${{ inputs.architecture }}"

    - uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"

    - run: dart pub get
      shell: bash

    - run: npm install
      shell: bash

    - uses: bufbuild/buf-setup-action@v1.30.0
      with: {github_token: "${{ inputs.github-token }}"}

    - name: Check out the language repo
      uses: sass/clone-linked-repo@v1
      with: {repo: sass/sass, path: build/language}

    - name: Generate deprecations from language repo.
      run: dart run grinder deprecations
      env: {UPDATE_SASS_SASS_REPO: false}
      shell: bash

    - name: Generate Dart from protobuf
      run: dart run grinder protobuf
      env: {UPDATE_SASS_SASS_REPO: false}
      shell: bash
