name: Build Protobuf
description: Check out and build the Dart Sass embedded protocol buffer.
inputs:
  github-token: {required: true}
runs:
  using: composite
  steps:
    - uses: bufbuild/buf-setup-action@v1.13.1
      with: {github_token: "${{ inputs.github-token }}"}

    - name: Check out embedded Sass protocol
      uses: sass/clone-linked-repo@v1
      with: {repo: sass/embedded-protocol, path: build/embedded-protocol}

    - name: Generate Dart from protobuf
      run: dart run grinder protobuf
      env: {UPDATE_SASS_PROTOCOL: false}
      shell: bash
