name: CI

on:
  push:
    branches: [main, feature.*]
    tags: ['[0-9]+.[0-9]+.*']
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      security-events: write # Forwarded
      actions: read # Forwarded
    uses: ./.github/workflows/test.yml

  dependabot_merge:
    name: Auto-merge Dependabot PR
    permissions:
      contents: write # Needed to merge PR
      pull-requests: write # Needed to merge PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'sass/dart-sass'

    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  double_check:
    name: Double-check
    runs-on: ubuntu-latest
    needs: [test]
    if: "github.ref_type == 'tag' && github.event.repository.fork == false"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: {persist-credentials: false}
      - uses: ./.github/util/initialize
        with: {github-token: "${{ github.token }}"}

      - name: Run checks
        run: dart run grinder double-check-before-release

  test_vendor:
    needs: [double_check]
    if: "github.ref_type == 'tag' && github.event.repository.fork == false"
    uses: ./.github/workflows/test-vendor.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [test_vendor]
    if: "github.ref_type == 'tag' && github.event.repository.fork == false"
    permissions:
      artifact-metadata: write # Forwarded
      attestations: write # Forwarded
      contents: write # Forwarded
      id-token: write # Forwarded
    uses: ./.github/workflows/release.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      CHOCOLATEY_TOKEN: ${{ secrets.CHOCOLATEY_TOKEN }}
      SASS_SITE_TOKEN: ${{ secrets.SASS_SITE_TOKEN }}
